services:
  rchan2:
    image: ghcr.io/rtainjapan/rchan2:latest
    container_name: rchan2
    environment:
      - DISCORD_GUILD_ID=
      - DISCORD_ROLE_ID=
      - DISCORD_TOKEN=
      - GOOGLE_SPREADSHEET_ID=
      - GOOGLE_SPREADSHEET_SHEETNAME=
      - GOOGLE_SPREADSHEET_COLUMNNAME=
      - GOOGLE_APIKEY=
      - CHECK_INTERVAL=
    restart: always
